services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: omega
    ports:
      - 27017:27017
  papilertus:
    image: papilertus:latest
    volumes:
      - ./config:/app/config
volumes:
  config:
